---
abstract: 'Plack application for running Tags::HTML objects.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Object: 0
  HTTP::Request::Common: 0
  Plack::Test: 0
  Tags::HTML: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Tags-HTML
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  English: 0
  Error::Pure: 0
  Plack::Component::Tags::HTML: 0.05
  Plack::Util::Accessor: 0
  Symbol::Get: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Plack-App-Tags-HTML/issues
  homepage: https://github.com/michal-josef-spacek/Plack-App-Tags-HTML
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Plack-App-Tags-HTML
version: '0.05'
